# Generated by Django 3.0.5 on 2024-02-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='user_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
